a

diff --git a/env/lib/R/bin/javareconf b/env/lib/R/bin/javareconf
--- a/env/lib/R/bin/javareconf
+++ b/env/lib/R/bin/javareconf
@@ -9,7 +9,7 @@ fi
 DYLIB_EXT=`${R_HOME}/bin/R CMD config DYLIB_EXT`
 tools_classpath=${R_SHARE_DIR}/java
 
-revision='$Rev: 84174 $'
+revision='$Rev: 74361 $'
 version=`set - ${revision}; echo ${2}`
 version="R Java configurator: ${R_VERSION} (r${version})
 
@@ -191,9 +191,9 @@ if test -z "$JAR"; then
 fi
 echo "Java archive tool: ${JAR}"
 
-: ${JAVA_LIBS='~autodetect~'}
-: ${JAVA_CPPFLAGS='~autodetect~'}
-: ${JAVA_LD_LIBRARY_PATH='~autodetect~'}
+: ${JAVA_LIBS=~autodetect~}
+: ${JAVA_CPPFLAGS=~autodetect~}
+: ${JAVA_LD_LIBRARY_PATH=~autodetect~}
 custom_JAVA_LIBS="${JAVA_LIBS}"
 custom_JAVA_CPPFLAGS="${JAVA_CPPFLAGS}"
 custom_JAVA_LD_LIBRARY_PATH="${JAVA_LD_LIBRARY_PATH}"
@@ -221,7 +221,7 @@ fi
 ## we now look for a path to put in R_LD_LIBRARY_PATH which will
 ## enable libjvm to be found at run time.  This should not be needed,
 ## but it seems that libjvm is often not in the ld.so cache.
-if test "${JAVA_LIBS}" = '~autodetect~'; then
+if test "${JAVA_LIBS}" = "~autodetect~"; then
 	## we need to reset LD_LIBRARY_PATH, because Java automatically
 	## adds all LD_LIBRARY_PATH to Java path
 	save_LDLP=${LD_LIBRARY_PATH}
@@ -255,9 +255,9 @@ if test "${JAVA_LIBS}" = '~autodetect~'; then
 	IFS=${save_IFS}
 	# replace occurrences of JAVA_HOME with $(JAVA_HOME)
 	# If JAVA_HOME was a link, it will be the canonical path we
-	# want to replace.  We need working realpath to determine what that is.
-	if /usr/bin/realpath "${JAVA_HOME}" >/dev/null 2>&1; then
-            java_home=`/usr/bin/realpath "${JAVA_HOME}"`
+	# want to replace.  We need realpath to determine what that is.
+	if test "false" != "false"; then
+             java_home=`false "${JAVA_HOME}"`
 	else
        	    java_home="${JAVA_HOME}"
 	fi
@@ -284,7 +284,7 @@ if test "${JAVA_LIBS}" = '~autodetect~'; then
            jmdinc=''
            jmdirs=''
 	   ## we are not in configure, so we need to find the OS from R
-	   host_os=`echo 'cat(R.version$os)'|${R_HOME}/bin/R --vanilla --no-echo 2>/dev/null`
+	   host_os=`echo 'cat(R.version$os)'|${R_HOME}/bin/R --vanilla --slave 2>/dev/null`
            ## put the most probable locations for each system in the first place
            case "${host_os}" in
              darwin*)  jmdirs=darwin;;
@@ -377,7 +377,7 @@ if test $ac_status != 0; then
 fi
 
 rm -f conftest.c conftest.o conftest.so Makevars
-cd "${wd}"
+cd ${wd}
 rm -Rf "${tempdir}"
 
 
@@ -419,15 +419,13 @@ else
   files="${R_HOME}/etc/Makeconf ${R_HOME}/etc/ldpaths"
 fi
 for file in $files; do
-    ${SED-sed} -e "s|JAVA =.\{0,\}|JAVA = $JAVA|" -e "s|JAVA_HOME =.\{0,\}|JAVA_HOME = ${JAVA_HOME}|" -e "s|: \${JAVA_HOME=.\{1,\}|: \${JAVA_HOME=${JAVA_HOME}}|" -e "s|: \${R_JAVA_LD_LIBRARY_PATH=.\{1,\}|: \${R_JAVA_LD_LIBRARY_PATH=${JAVA_LD_LIBRARY_PATH_SH}}|" -e "s|JAVA_LIBS =.\{0,\}|JAVA_LIBS = ${JAVA_LIBS}|g" -e "s|JAVA_LD_LIBRARY_PATH =.\{0,\}|JAVA_LD_LIBRARY_PATH = ${JAVA_LD_LIBRARY_PATH}|" -e "s|JAVAC =.\{0,\}|JAVAC = $JAVAC|" -e "s|JAVAH =.\{0,\}|JAVAH = $JAVAH|" -e "s|JAR =.\{0,\}|JAR = $JAR|" -e "s|JAVA_CPPFLAGS =.\{0,\}|JAVA_CPPFLAGS = ${JAVA_CPPFLAGS}|g"  "${file}" | cmp -s - "${file}" || {
-    ${SED-sed} -e "s|JAVA =.\{0,\}|JAVA = $JAVA|" -e "s|JAVA_HOME =.\{0,\}|JAVA_HOME = ${JAVA_HOME}|" -e "s|: \${JAVA_HOME=.\{1,\}|: \${JAVA_HOME=${JAVA_HOME}}|" -e "s|: \${R_JAVA_LD_LIBRARY_PATH=.\{1,\}|: \${R_JAVA_LD_LIBRARY_PATH=${JAVA_LD_LIBRARY_PATH_SH}}|" -e "s|JAVA_LIBS =.\{0,\}|JAVA_LIBS = ${JAVA_LIBS}|g" -e "s|JAVA_LD_LIBRARY_PATH =.\{0,\}|JAVA_LD_LIBRARY_PATH = ${JAVA_LD_LIBRARY_PATH}|" -e "s|JAVAC =.\{0,\}|JAVAC = $JAVAC|" -e "s|JAVAH =.\{0,\}|JAVAH = $JAVAH|" -e "s|JAR =.\{0,\}|JAR = $JAR|" -e "s|JAVA_CPPFLAGS =.\{0,\}|JAVA_CPPFLAGS = ${JAVA_CPPFLAGS}|g"  "${file}" > "${file}.$$"
-    if test -f "${file}.$$"; then
-	mv -f "${file}.$$" "${file}"
-     else
-	echo "*** cannot create ${file}.$$~*** Please run as root if required.~" | ${SED-sed} -e 'y/~/\n/' >&2
- 	exit 1
-     fi
-    }
+    ${SED-sed} -e "s|JAVA =.\{0,\}|JAVA = $JAVA|" -e "s|JAVA_HOME =.\{0,\}|JAVA_HOME = ${JAVA_HOME}|" -e "s|: \${JAVA_HOME=.\{1,\}|: \${JAVA_HOME=${JAVA_HOME}}|" -e "s|: \${R_JAVA_LD_LIBRARY_PATH=.\{1,\}|: \${R_JAVA_LD_LIBRARY_PATH=${JAVA_LD_LIBRARY_PATH_SH}}|" -e "s|JAVA_LIBS =.\{0,\}|JAVA_LIBS = ${JAVA_LIBS}|g" -e "s|JAVA_LD_LIBRARY_PATH =.\{0,\}|JAVA_LD_LIBRARY_PATH = ${JAVA_LD_LIBRARY_PATH}|" -e "s|JAVAC =.\{0,\}|JAVAC = $JAVAC|" -e "s|JAVAH =.\{0,\}|JAVAH = $JAVAH|" -e "s|JAR =.\{0,\}|JAR = $JAR|" -e "s|JAVA_CPPFLAGS =.\{0,\}|JAVA_CPPFLAGS = ${JAVA_CPPFLAGS}|g"  "${file}" > "${file}.new"
+    if test -f "${file}.new"; then
+	mv "${file}.new" "${file}"
+    else
+	echo "*** cannot create ${file}.new~*** Please run as root if required.~" | ${SED-sed} -e 'y/~/\n/' >&2
+	exit 1
+    fi
 done
 
 echo "Done."
